### ISSUE TITLE
Missing assets

### ISSUE THREAD

**Issue by Lukortech** [sylvainpolletvillard/pwa-workshop#1]
Hi! Just wanted to give a bit of heads up on missing assets at the very end of the [https://pwa-workshop.js.org/6-pwa-setup/](https://pwa-workshop.js.org/6-pwa-setup/).

If you're feeling like it, it would be awesome to have thos .pngs back on page :)

![Zrzut ekranu z 2019-12-09 09-51-32](https://user-images.githubusercontent.com/26508593/70421252-c360a300-1a69-11ea-90be-fe759f982bad.png)
![Zrzut ekranu z 2019-12-09 09-50-21](https://user-images.githubusercontent.com/26508593/70421253-c3f93980-1a69-11ea-99e2-1d3ab64ad1c6.png)

**Comment by sylvainpolletvillard** [comment]
Hey, thanks for the report. It should be fixed now !

**Comment by Lukortech** [comment]
Thanks! 
Cheers
