### ISSUE TITLE
translate workshop 

### ISSUE THREAD

**Issue by sabermazoji** [sylvainpolletvillard/pwa-workshop#3]
Hi sylvainpolletvillard, 
thanks for the great tutorial, I wanna translate this workshop to Persian what is the best way for it? I should create a "fa" folder?

**Comment by sylvainpolletvillard** [comment]
Hello @sabermazoji 

That would be great ! Yes, you can follow these instructions to add other languages: https://vuepress.vuejs.org/guide/i18n.html

**Comment by sylvainpolletvillard** [comment]
Hey @sabermazoji , still motivated on this topic ? or I can close the issue ?
